name: UniMo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - expat=2.7.0=h5888daf_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - gcc=10.4.0=hb92f740_13
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.14=h5888daf_0
  - gxx=10.4.0=hb92f740_13
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - harfbuzz=11.2.1=h3beb420_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h0aef613_1
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=15.1.0=h69a702a_3
  - libglib=2.84.2=h3618099_0
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libpng=1.6.50=h943b412_0
  - libsanitizer=10.4.0=h5246dfb_19
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=15.1.0=h4852527_3
  - libtiff=4.7.0=he137b08_1
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.4=h6a678d5_0
  - openjdk=17.0.15=h5ddf6bc_0
  - openssl=3.5.1=h7b32b05_0
  - pcre2=10.45=hc749103_0
  - pip=25.1=pyhc872135_2
  - pixman=0.46.2=h29eaf8c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.13=hd12c33a_1_cpython
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.2=h2c6b66d_0
  - sysroot_linux-64=2.17=h0157908_18
  - tk=8.6.13=noxft_hd72426e_102
  - unzip=6.0=h611a1e1_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zip=3.0=h7f8727e_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiohttp-cors==0.8.1
      - aiosignal==1.3.2
      - airportsdata==20250622
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - astor==0.8.1
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - bert-score==0.3.13
      - bitsandbytes==0.46.0
      - blake3==1.0.5
      - bleach==6.2.0
      - blis==0.7.11
      - boto3==1.38.45
      - botocore==1.38.45
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.6.15
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.2.1
      - clip==1.0
      - cloudpathlib==0.16.0
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - comm==0.2.2
      - compressed-tensors==0.9.1
      - confection==0.1.5
      - contourpy==1.3.2
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - cymem==2.0.11
      - datasets==3.6.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - deepspeed==0.15.4
      - defusedxml==0.7.1
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distilabel==1.5.3
      - distlib==0.3.9
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.115.14
      - fastapi-cli==0.0.7
      - fastjsonschema==2.21.1
      - fastrlock==0.8.3
      - filelock==3.18.0
      - flake8==7.3.0
      - flash-attn==2.8.0.post2
      - fonttools==4.58.5
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.33.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - ipykernel==6.29.5
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - isort==6.0.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - lark==1.2.2
      - latex2sympy2-extended==1.0.6
      - liger-kernel==0.5.2
      - lightning-utilities==0.14.3
      - linkify-it-py==2.0.3
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.11
      - lxml==6.0.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - math-verify==0.5.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - memray==1.17.2
      - mistral-common==1.6.2
      - mistune==3.1.3
      - modelscope==1.27.1
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.0
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - notebook==7.4.3
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.5.2
      - openai==1.92.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - orjson==3.10.18
      - outlines==0.1.11
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parameterized==0.9.0
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - peft==0.14.0
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - portalocker==3.2.0
      - preshed==3.0.10
      - prettytable==3.16.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==2.13.6
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pycodestyle==2.14.0
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyecharts==2.0.8
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pynvml==12.0.0
      - pyparsing==3.2.3
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - ray==2.40.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rich-toolkit==0.14.7
      - rouge==1.0.1
      - rouge-score==0.1.2
      - rpds-py==0.25.1
      - rsa==4.9.1
      - ruff==0.12.1
      - s3transfer==0.13.0
      - safetensors==0.5.3
      - scipy==1.11.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.32.0
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - simplejson==3.20.1
      - six==1.17.0
      - smart-open==6.4.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - starlette==0.46.2
      - swankit==0.2.4
      - swanlab==0.6.4
      - sympy==1.13.1
      - tblib==3.1.0
      - tensorboardx==2.6.4
      - terminado==0.18.1
      - textual==3.5.0
      - thinc==8.0.17
      - tiktoken==0.9.0
      - tinycss2==1.4.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1
      - torchmetrics==1.7.3
      - torchvision==0.20.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.1.0
      - trl==0.18.0
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - universal-pathlib==0.2.6
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.34.3
      - uvloop==0.21.0
      - virtualenv==20.31.2
      - vllm==0.7.3
      - wandb==0.20.1
      - wasabi==0.10.1
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - weasel==0.3.4
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.11
      - xlsxwriter==3.2.5
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
